module.exports = {

    //     // ########################
    //     // #### Value Look Ups ####
    //     // ########################
    CHOICES_FILTER: [
        { id: '0', label: 'Through' },
        { id: '1', label: '1/4' },
        { id: '2', label: '1/16' },
        { id: '3', label: '1/64' },
        { id: '4', label: '1/8' },
        { id: '8', label: 'AUTO' }
    ],

    CHOICES_SHUTTER: [
        { id: '0', label: 'OFF' },
        { id: '2', label: '1/60' },
        { id: '3', label: '1/100' },
        { id: '4', label: '1/120' },
        { id: '5', label: '1/250' },
        { id: '6', label: '1/500' },
        { id: '7', label: '1/1000' },
        { id: '8', label: '1/2000' },
        { id: '9', label: '1/4000' },
        { id: 'A', label: '1/10000' },
        { id: 'B', label: 'Syncro Scan' },
        { id: 'C', label: 'ELC' },
        { id: 'D', label: '1/24' },
        { id: 'E', label: '1/25' },
        { id: 'F', label: '1/30' }
    ],

    CHOICES_PSSPEED: [
        { id: 999, label: 'Speed (Fast)' },
        { id: 975, label: 'Speed 30' },
        { id: 950, label: 'Speed 29' },
        { id: 925, label: 'Speed 28' },
        { id: 900, label: 'Speed 27' },
        { id: 875, label: 'Speed 26' },
        { id: 850, label: 'Speed 25' },
        { id: 825, label: 'Speed 24' },
        { id: 800, label: 'Speed 23' },
        { id: 775, label: 'Speed 22' },
        { id: 750, label: 'Speed 21' },
        { id: 725, label: 'Speed 20' },
        { id: 700, label: 'Speed 19' },
        { id: 675, label: 'Speed 18' },
        { id: 650, label: 'Speed 17' },
        { id: 625, label: 'Speed 16' },
        { id: 600, label: 'Speed 15' },
        { id: 575, label: 'Speed 14' },
        { id: 550, label: 'Speed 13' },
        { id: 525, label: 'Speed 12' },
        { id: 500, label: 'Speed 11' },
        { id: 475, label: 'Speed 10' },
        { id: 450, label: 'Speed 09' },
        { id: 425, label: 'Speed 08' },
        { id: 400, label: 'Speed 07' },
        { id: 375, label: 'Speed 06' },
        { id: 350, label: 'Speed 05' },
        { id: 325, label: 'Speed 04' },
        { id: 300, label: 'Speed 03' },
        { id: 275, label: 'Speed 02' },
        { id: 250, label: 'Speed 01 (Slow)' }
    ],

    CHOICES_SPEED: [
        { id: 49, label: 'Speed 49 (Fast)' },
        { id: 48, label: 'Speed 48' },
        { id: 47, label: 'Speed 47' },
        { id: 46, label: 'Speed 46' },
        { id: 45, label: 'Speed 45' },
        { id: 44, label: 'Speed 44' },
        { id: 43, label: 'Speed 43' },
        { id: 42, label: 'Speed 42' },
        { id: 41, label: 'Speed 41' },
        { id: 40, label: 'Speed 40' },
        { id: 39, label: 'Speed 39' },
        { id: 38, label: 'Speed 38' },
        { id: 37, label: 'Speed 37' },
        { id: 36, label: 'Speed 36' },
        { id: 35, label: 'Speed 35' },
        { id: 34, label: 'Speed 34' },
        { id: 33, label: 'Speed 33' },
        { id: 32, label: 'Speed 32' },
        { id: 31, label: 'Speed 31' },
        { id: 30, label: 'Speed 30' },
        { id: 29, label: 'Speed 29' },
        { id: 28, label: 'Speed 28' },
        { id: 27, label: 'Speed 27' },
        { id: 26, label: 'Speed 26' },
        { id: 25, label: 'Speed 25' },
        { id: 24, label: 'Speed 24' },
        { id: 23, label: 'Speed 23' },
        { id: 22, label: 'Speed 22' },
        { id: 21, label: 'Speed 21' },
        { id: 20, label: 'Speed 20' },
        { id: 19, label: 'Speed 19' },
        { id: 18, label: 'Speed 18' },
        { id: 17, label: 'Speed 17' },
        { id: 16, label: 'Speed 16' },
        { id: 15, label: 'Speed 15' },
        { id: 14, label: 'Speed 14' },
        { id: 13, label: 'Speed 13' },
        { id: 12, label: 'Speed 12' },
        { id: 11, label: 'Speed 11' },
        { id: 10, label: 'Speed 10' },
        { id: 9, label: 'Speed 09' },
        { id: 8, label: 'Speed 08' },
        { id: 7, label: 'Speed 07' },
        { id: 6, label: 'Speed 06' },
        { id: 5, label: 'Speed 05' },
        { id: 4, label: 'Speed 04' },
        { id: 3, label: 'Speed 03' },
        { id: 2, label: 'Speed 02' },
        { id: 1, label: 'Speed 01 (Slow)' },
        { id: 0, label: 'Stop' }
    ],

    CHOICES_GAIN: [
        { id: '08', label: '0dB' },
        { id: '09', label: '1dB' },
        { id: '0A', label: '2dB' },
        { id: '0B', label: '3db' },
        { id: '0C', label: '4dB' },
        { id: '0D', label: '5dB' },
        { id: '0E', label: '6dB' },
        { id: '0F', label: '7dB' },
        { id: '10', label: '8dB' },
        { id: '11', label: '9dB' },
        { id: '12', label: '10dB' },
        { id: '13', label: '11dB' },
        { id: '14', label: '12dB' },
        { id: '15', label: '13dB' },
        { id: '16', label: '14dB' },
        { id: '17', label: '15dB' },
        { id: '18', label: '16dB' },
        { id: '19', label: '17dB' },
        { id: '1A', label: '18dB' },
        { id: '1B', label: '19dB' },
        { id: '1C', label: '20dB' },
        { id: '1D', label: '21dB' },
        { id: '1E', label: '22dB' },
        { id: '1F', label: '23dB' },
        { id: '20', label: '24dB' },
        { id: '21', label: '25dB' },
        { id: '22', label: '26dB' },
        { id: '23', label: '27dB' },
        { id: '24', label: '28dB' },
        { id: '25', label: '29dB' },
        { id: '26', label: '30dB' },
        { id: '27', label: '31dB' },
        { id: '28', label: '32dB' },
        { id: '29', label: '33dB' },
        { id: '2A', label: '34dB' },
        { id: '2B', label: '35dB' },
        { id: '2C', label: '36dB' },
        { id: '2D', label: '37dB' },
        { id: '2E', label: '38dB' },
        { id: '2F', label: '39dB' },
        { id: '30', label: '40dB' },
        { id: '31', label: '41dB' },
        { id: '32', label: '42dB' },
        { id: '33', label: '43dB' },
        { id: '34', label: '44dB' },
        { id: '35', label: '45dB' },
        { id: '36', label: '46dB' },
        { id: '37', label: '47dB' },
        { id: '38', label: '48dB' },
        { id: '80', label: 'Auto' }
    ]
}  