import { c } from './choices.js'

export const MODELS = [
	{ id: 'Auto', series: 'Auto', label: 'Auto Detect' },
	{ id: 'AW-HE2', series: 'HE2', label: 'AW-HE2' },
	{ id: 'AW-HE20', series: 'UE20', label: 'AW-HE20' },
	{ id: 'AW-HE35', series: 'HE40', label: 'AW-HE35' },
	{ id: 'AW-HE38', series: 'HE40', label: 'AW-HE38' },
	{ id: 'AW-HE40', series: 'HE40', label: 'AW-HE40' },
	{ id: 'AW-HE42', series: 'HE42', label: 'AW-HE42' },
	{ id: 'AW-HE48', series: 'HE40', label: 'AW-HE48' },
	{ id: 'AW-HE50', series: 'HE50', label: 'AW-HE50' },
	{ id: 'AW-HE58', series: 'HE40', label: 'AW-HE58' },
	{ id: 'AW-HE60', series: 'HE60', label: 'AW-HE60' },
	{ id: 'AW-HE65', series: 'HE40', label: 'AW-HE65' },
	{ id: 'AW-HE68', series: 'HE42', label: 'AW-HE68' },
	{ id: 'AW-HE70', series: 'HE40', label: 'AW-HE70' },
	{ id: 'AW-HE75', series: 'HE42', label: 'AW-HE75' },
	{ id: 'AW-HE120', series: 'HE120', label: 'AW-HE120' },
	{ id: 'AW-HE130', series: 'HE130', label: 'AW-HE130' },
	{ id: 'AW-HE145', series: 'UE150', label: 'AW-HE145' },
	{ id: 'AW-HN38', series: 'HE40', label: 'AW-HN38' },
	{ id: 'AW-HN40', series: 'HE40', label: 'AW-HN40' },
	{ id: 'AW-HN65', series: 'HE40', label: 'AW-HN65' },
	{ id: 'AW-HN130', series: 'HE130', label: 'AW-HN130' },
	{ id: 'AW-HR140', series: 'HR140', label: 'AW-HR140' },
	{ id: 'AW-UE4', series: 'UE4', label: 'AW-UE4' },
	{ id: 'AW-UE20', series: 'UE20', label: 'AW-UE20' },
	{ id: 'AW-UE40', series: 'UE80', label: 'AW-UE40' },
	{ id: 'AW-UE50', series: 'UE80', label: 'AW-UE50' },
	{ id: 'AW-UE63', series: 'UE70', label: 'AW-UE63' },
	{ id: 'AW-UE65', series: 'UE70', label: 'AW-UE65' },
	{ id: 'AW-UE70', series: 'UE70', label: 'AW-UE70' },
	{ id: 'AW-UE80', series: 'UE80', label: 'AW-UE80' },
	{ id: 'AW-UE100', series: 'UE150', label: 'AW-UE100' },
	{ id: 'AW-UE150', series: 'UE150', label: 'AW-UE150' },
	{ id: 'AW-UE155', series: 'UE150', label: 'AW-UE155' },
	{ id: 'AW-UE160', series: 'UE160', label: 'AW-UE160' },
	{ id: 'AW-UN70', series: 'UE70', label: 'AW-UN70' },
	{ id: 'AW-UN145', series: 'UE150', label: 'AW-UN145' },
	{ id: 'AW-UR100', series: 'UE150', label: 'AW-UR100' },
	{ id: 'AK-UB300', series: 'UB300', label: 'AK-UB300' },
	{ id: 'AG-CX350', series: 'CX350', label: 'AG-CX350' },
	{ id: 'AG-CX200', series: 'CX350', label: 'AG-CX200' },
	{ id: 'AJ-UPX360', series: 'CX350', label: 'AJ-UPX360' },
	{ id: 'AJ-CX4000', series: 'CX350', label: 'AJ-CX4000' },
	{ id: 'AJ-UPX900', series: 'CX350', label: 'AJ-UPX900' },
	{ id: 'Other', series: 'Other', label: 'Other Cameras' },
]

// list of all Series:
// Other
// HE2
// HE40
// HE42
// HE50
// HE60
// HE120
// HE130
// UE20
// UE70
// UE80
// UE150
// UE160
// HR140
// UE4
// UB300
// CX350

export const SERIES_SPECS = [
	{
		// Includes all Actions / Variables / Feedbacks
		id: 'Other',
		variables: {
			version: true, // If a camera sends a package every minute with the firmware version (qSV3)
			error: true, // Camera can return Error messages when actions fail (rER)
			ins: true, // Install position (iNS0 or iNS1)
			power: true, // Power State (p1 or p0)
			colorbar: true, // Color Bar State (OBR:1 or OBR:0)
			tally: true, // Red Tally State (DA1/TLR:1 or DA0/TLR:0)
			tally2: true, // Green Tally State (TLG:1 or TLG:0)
			OAF: true, // Has Auto Focus (OAF:1 or OAF:0)
			iris: true, // Has Auto Iris (d30 or d31)
			gainValue: true,
			preset: true,
			whiteBalance: true,  // Has White Balance (OAW:x)
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true, // Power State (p1 or p0)
			colorbarState: true, // Color Bar State (OBR:1 or OBR:0)
			tallyState: true, // Red Tally State (dA1/TLR:1 or dA0/TLR:0)
			tally2State: true, // Green Tally State (TLG:1 or TLG:0)
			insState: true, // Install position (iNS0 or iNS1)
			autoFocus: true, // Has Auto Focus (OAF:1 or OAF:0)
			autoIris: true, // Has Auto Iris (d30 or d31)
			whiteBalance: true,  // Has White Balance (OAW:x)
			preset: true,
		},
		actions: {
			panTilt: true, // Has Pan/Tilt Support (PTSxx)
			ptSpeed: true, // Internal Speed Options
			zoom: true, // Has Zoom Support (Zxx)
			zSpeed: true, // Internal Speed Options
			focus: true, // Has Focus Support (Fxx)
			fSpeed: true, // Internal Speed Options
			OAF: true, // Has Auto Focus Support (D10 or D11)
			OTAF: true, // Has One Touch Auto Focus Support (OSE:69:1)
			iris: true, // Has Iris Support (manual and auto) (Ixx)
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_OTHER() }, // Has Gain Support
			shut: { cmd: 'OSH:', dropdown: c.CHOICES_SHUTTER_OTHER }, // Has Shutter Support
			ped: { cmd: 'OTP:', dropdown: c.CHOICES_PEDESTAL_OTHER() }, // Has Pedestal Support
			filter: { cmd: 'OFT:', dropdown: c.CHOICES_FILTER_OTHER }, // Has ND Filter Support
			preset: true, // Can Save and Recall Presets (Mxxx or Rxxx)
			speedPset: true, // Has Preset Recall Speed Control (UPVSxx)
			timePset: true, // Has Preset Recall Time Control (UPVSxx or OSJ:29:xx)
			power: true, // Has Power Control (O0 or O1)
			colorbar: true, // Has Color Bar Control (DCB:1 or DCB:0)
			tally: true, // Has Red Tally Light Control (DA1/TLR:1 or DA0/TLR:0)
			tally2: true, // Has Green Tally Light Control (TLG:1 or TLG:0)
			ins: true, // Has Install Position Control (INSx)
			sdCard: true, // Has SD Card Recording Control (sdctrl?save=start or sdctrl?save=end)
			whiteBalance: { dropdown: c.CHOICES_WB_SET },  // Has White Balance Control (OAW:x)
			colorTemperature: false, // Setting Color temperature OSD:B1:A8h
		},
	},

	{
		// Specific for the HE40 Series
		id: 'HE40',
		variables: {
			version: true,
			error: true,
			ins: true,
			power: true,
			colorbar: true,
			tally: true,
			OAF: true,
			iris: true,
			gainValue: true,
			preset: true,
			whiteBalance: true,
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			tallyState: true,
			insState: true,
			autoFocus: true,
			autoIris: true,
			whiteBalance: true,
			preset: true,
		},
		actions: {
			panTilt: true,
			ptSpeed: true,
			zoom: true,
			zSpeed: true,
			focus: true,
			fSpeed: true,
			OAF: true,
			OTAF: true,
			iris: true,
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_HE40 },
			shut: { cmd: 'OSH:', dropdown: c.CHOICES_SHUTTER_HE40 },
			ped: { cmd: 'OTP:', dropdown: c.CHOICES_PEDESTAL_HE40() },
			filter: false,
			preset: true,
			speedPset: true,
			timePset: false,
			power: true,
			colorbar: true,
			tally: true,
			ins: true,
			sdCard: true,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: false,
		},
	},

	{
		// Specific for the HE42 Series
		id: 'HE42',
		variables: {
			version: true,
			error: true,
			ins: true,
			power: true,
			colorbar: true,
			tally: true,
			OAF: true,
			iris: true,
			gainValue: true,
			preset: true,
			whiteBalance: true,
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			tallyState: true,
			insState: true,
			autoFocus: true,
			autoIris: true,
			whiteBalance: true,
			preset: true,
		},
		actions: {
			panTilt: true,
			ptSpeed: true,
			zoom: true,
			zSpeed: true,
			focus: true,
			fSpeed: true,
			OAF: true,
			OTAF: true,
			iris: true,
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_HE40 },
			shut: { cmd: 'OSH:', dropdown: c.CHOICES_SHUTTER_HE40 },
			ped: { cmd: 'OTP:', dropdown: c.CHOICES_PEDESTAL_HE40() },
			filter: { cmd: 'OFT:', dropdown: c.CHOICES_FILTER_3A },
			preset: true,
			speedPset: true,
			timePset: false,
			power: true,
			colorbar: true,
			tally: true,
			ins: true,
			sdCard: true,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: false,
		},
	},

	{
		// Specific for the UE70 Series
		id: 'UE70',
		variables: {
			version: true,
			error: true,
			ins: true,
			power: true,
			colorbar: true,
			tally: true,
			OAF: true,
			iris: true,
			gainValue: true,
			preset: true,
			whiteBalance: true,
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			tallyState: true,
			insState: true,
			autoFocus: true,
			autoIris: true,
			whiteBalance: true,
			preset: true,
		},
		actions: {
			panTilt: true,
			ptSpeed: true,
			zoom: true,
			zSpeed: true,
			focus: true,
			fSpeed: true,
			OAF: true,
			OTAF: true,
			iris: true,
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_HE40 },
			shut: { cmd: 'OSH:', dropdown: c.CHOICES_SHUTTER_HE40 },
			ped: { cmd: 'OTP:', dropdown: c.CHOICES_PEDESTAL_HE40() },
			filter: { cmd: 'OFT:', dropdown: c.CHOICES_FILTER_3A },
			preset: true,
			speedPset: true,
			timePset: false,
			power: true,
			colorbar: true,
			tally: true,
			ins: true,
			sdCard: true,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: false,
		},
	},

	{
		// Specific for the UE150 Series
		id: 'UE150',
		variables: {
			version: true,
			error: true,
			ins: true,
			power: true,
			colorbar: true,
			tally: true,
			tally2: true,
			OAF: true,
			iris: true,
			gainValue: true,
			preset: true,
			whiteBalance: true,
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			tallyState: true,
			tally2State: true,
			insState: true,
			autoFocus: true,
			autoIris: true,
			whiteBalance: true,
			preset: true,
		},
		actions: {
			panTilt: true,
			ptSpeed: true,
			zoom: true,
			zSpeed: true,
			focus: true,
			fSpeed: true,
			OAF: true,
			OTAF: true,
			iris: true,
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_UE150 },
			shut: { cmd: 'OSJ:06:', dropdown: c.CHOICES_SHUTTER_UE150() },
			ped: { cmd: 'OSJ:0F:', dropdown: c.CHOICES_PEDESTAL_UE150() },
			filter: { cmd: 'OFT:', dropdown: c.CHOICES_FILTER_3 },
			preset: true,
			speedPset: true,
			timePset: true,
			power: true,
			ins: true,
			colorbar: true,
			tally: true,
			tally2: true,
			sdCard: false,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: false,
		},
	},

	{
		// Specific for the UE150 Series
		id: 'UE160',
		variables: {
			version: true,
			error: true,
			ins: true,
			power: true,
			colorbar: true,
			tally: true,
			tally2: true,
			tally3: true,
			OAF: true,
			iris: true,
			gainValue: true,
			preset: true,
			whiteBalance: true,
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			tallyState: true,
			tally2State: true,
			tally3State: true,
			insState: true,
			autoFocus: true,
			autoIris: true,
			whiteBalance: true,
			preset: true,
		},
		actions: {
			panTilt: true,
			ptSpeed: true,
			zoom: true,
			zSpeed: true,
			focus: true,
			fSpeed: true,
			OAF: true,
			OTAF: true,
			iris: true,
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_UE160 },
			shut: { cmd: 'OSJ:06:', dropdown: c.CHOICES_SHUTTER_UE150() },
			ped: { cmd: 'OSJ:0F:', dropdown: c.CHOICES_PEDESTAL_UE150() },
			filter: { cmd: 'OFT:', dropdown: c.CHOICES_FILTER_3 },
			preset: true,
			speedPset: true,
			timePset: true,
			power: true,
			ins: true,
			colorbar: true,
			tally: true,
			tally2: true,
			tally3: true,
			sdCard: false,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: false,
		},
	},

	{
		// Specific for the AW-HE2 Camera
		id: 'HE2', // A lot has been turned off since it will need custop setups for this camera, can be added if requested
		variables: {
			version: true,
			error: true,
			ins: false,
			power: true,
			colorbar: true,
			tally: true,
			OAF: false,
			iris: true,
			gainValue: true,
			preset: true,
			whiteBalance: true,
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			tallyState: true,
			insState: false,
			autoFocus: false,
			autoIris: true,
			whiteBalance: true,
			preset: true,
		},
		actions: {
			panTilt: true,
			ptSpeed: true,
			zoom: true,
			zSpeed: true,
			focus: false,
			fSpeed: false,
			OAF: false,
			OTAF: false,
			iris: true, // Might not work correctly (Auto/Manual should work though)
			gain: false,
			shut: false,
			ped: false,
			filter: false,
			preset: true,
			speedPset: false,
			timePset: false,
			power: true,
			colorbar: true,
			tally: true,
			ins: false,
			sdCard: false,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: false,
		},
	},

	{
		// Specific for the AW-HE50 Camera
		id: 'HE50',
		variables: {
			version: true,
			error: true,
			ins: true,
			power: true,
			colorbar: true,
			tally: true,
			OAF: true,
			iris: true,
			gainValue: true,
			preset: true,
			whiteBalance: true,
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			tallyState: true,
			insState: true,
			autoFocus: true,
			autoIris: true,
			whiteBalance: true,
			preset: true,
		},
		actions: {
			panTilt: true,
			ptSpeed: true,
			zoom: true,
			zSpeed: true,
			focus: true,
			fSpeed: true,
			OAF: true,
			OTAF: true,
			iris: true,
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_HE50 },
			shut: { cmd: 'OSH:', dropdown: c.CHOICES_SHUTTER_HE40 },
			ped: { cmd: 'OTP:', dropdown: c.CHOICES_PEDESTAL_HE40() },
			filter: false,
			preset: true,
			speedPset: true,
			timePset: false,
			power: true,
			colorbar: true,
			tally: true,
			ins: true,
			sdCard: false,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: false,
		},
	},

	{
		// Specific for the AW-HE60 Camera
		id: 'HE60',
		variables: {
			version: true,
			error: true,
			ins: true,
			power: true,
			colorbar: true,
			tally: true,
			OAF: true,
			iris: true,
			gainValue: true,
			preset: true,
			whiteBalance: true,
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			tallyState: true,
			insState: true,
			autoFocus: true,
			autoIris: true,
			whiteBalance: true,
			preset: true,
		},
		actions: {
			panTilt: true,
			ptSpeed: true,
			zoom: true,
			zSpeed: true,
			focus: true,
			fSpeed: true,
			OAF: true,
			OTAF: true,
			iris: true,
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_HE50 },
			shut: { cmd: 'OSH:', dropdown: c.CHOICES_SHUTTER_HE40 },
			ped: { cmd: 'OTP:', dropdown: c.CHOICES_PEDESTAL_HE40() },
			filter: false,
			preset: true,
			speedPset: true,
			timePset: false,
			power: true,
			colorbar: true,
			tally: true,
			ins: true,
			sdCard: false,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: false,
		},
	},

	{
		// Specific for the AW-HE120 Camera
		id: 'HE120',
		variables: {
			version: true,
			error: true,
			ins: true,
			power: true,
			colorbar: true,
			tally: true,
			OAF: true,
			iris: true,
			gainValue: true,
			preset: true,
			whiteBalance: true,
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			tallyState: true,
			insState: true,
			autoFocus: true,
			autoIris: true,
			whiteBalance: true,
			preset: true,
		},
		actions: {
			panTilt: true,
			ptSpeed: true,
			zoom: true,
			zSpeed: true,
			focus: true,
			fSpeed: true,
			OAF: true,
			OTAF: true,
			iris: true,
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_HE120 },
			shut: { cmd: 'OSH:', dropdown: c.CHOICES_SHUTTER_HE120 },
			ped: { cmd: 'OTP:', dropdown: c.CHOICES_PEDESTAL_HE120() },
			filter: { cmd: 'OFT:', dropdown: c.CHOICES_FILTER_3 },
			preset: true,
			speedPset: true,
			timePset: false,
			power: true,
			colorbar: true,
			tally: true,
			ins: true,
			sdCard: false,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: false,
		},
	},

	{
		// Specific for the AW-HE130 Camera
		id: 'HE130',
		variables: {
			version: true,
			error: true,
			ins: true,
			power: true,
			colorbar: true,
			tally: true,
			OAF: true,
			iris: true,
			gainValue: true,
			preset: true,
			whiteBalance: true,
			colorTemperature: true,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			tallyState: true,
			insState: true,
			autoFocus: true,
			autoIris: true,
			whiteBalance: true,
			preset: true,
		},
		actions: {
			panTilt: true,
			ptSpeed: true,
			zoom: true,
			zSpeed: true,
			focus: true,
			fSpeed: true,
			OAF: true,
			OTAF: true,
			iris: true,
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_HE130 },
			shut: { cmd: 'OSH:', dropdown: c.CHOICES_SHUTTER_HE130 },
			ped: { cmd: 'OTP:', dropdown: c.CHOICES_PEDESTAL_HE120() },
			filter: { cmd: 'OFT:', dropdown: c.CHOICES_FILTER_2 },
			preset: true,
			speedPset: true,
			timePset: false,
			power: true,
			colorbar: true,
			tally: true,
			ins: true,
			sdCard: false,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: { cmd: 'OSD:B1:', dropdown: c.CHOICES_COLOR_TEMPERATURE_HE130 },
		},
	},

	{
		// Specific for the AW-HR140 Camera
		id: 'HR140',
		variables: {
			version: true,
			error: true,
			ins: true,
			power: true,
			colorbar: true,
			tally: true,
			OAF: true,
			iris: true,
			gainValue: true,
			preset: true,
			whiteBalance: true,
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			tallyState: true,
			insState: true,
			autoFocus: true,
			autoIris: true,
			whiteBalance: true,
			preset: true,
		},
		actions: {
			panTilt: true,
			ptSpeed: true,
			zoom: true,
			zSpeed: true,
			focus: true,
			fSpeed: true,
			OAF: true,
			OTAF: true,
			iris: true,
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_HR140 },
			shut: { cmd: 'OSH:', dropdown: c.CHOICES_SHUTTER_HE130 },
			ped: { cmd: 'OTP:', dropdown: c.CHOICES_PEDESTAL_HE120() },
			filter: { cmd: 'OFT:', dropdown: c.CHOICES_FILTER_2 },
			preset: true,
			speedPset: true,
			timePset: false,
			power: true,
			colorbar: true,
			tally: true,
			ins: true,
			sdCard: false,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: false,
		},
	},

	{
		// Specific for the AW-UE4 Camera
		id: 'UE4', // A lot has been turned off since it will need custop setups for this camera, can be added if requested
		variables: {
			version: false,
			error: true,
			ins: true,
			power: true,
			colorbar: true,
			tally: true,
			OAF: false,
			iris: true,
			gainValue: true,
			preset: true,
			whiteBalance: true,
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			tallyState: true,
			insState: true,
			autoFocus: false,
			autoIris: true,
			whiteBalance: true,
			preset: true,
		},
		actions: {
			panTilt: true,
			ptSpeed: true,
			zoom: true,
			zSpeed: true,
			focus: true,
			fSpeed: true,
			OAF: false,
			OTAF: false,
			iris: true, // Might not work correctly (Auto/Manual should work though)
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_UE4 },
			shut: { cmd: 'OSJ:06:', dropdown: c.CHOICES_SHUTTER_UE4 },
			ped: false,
			filter: false,
			preset: true,
			speedPset: false,
			timePset: false,
			power: true,
			colorbar: true,
			tally: true,
			ins: true,
			sdCard: false,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: false,
		},
	},

	{
		// Specific for the AK-UB300 Camera
		id: 'UB300',
		variables: {
			version: false,
			error: true,
			power: true,
			colorbar: true,
			tally: true,
			tally2: true,
			ins: false,
			OAF: false,
			iris: false,
			preset: false,
			whiteBalance: false,
			colorTemperature: false,
		},
		feedbacks: {
			powerState: true,
			colorbarState: true,
			insState: false,
			autoFocus: false,
			autoIris: false,
			whiteBalance: false,
			preset: false,
		},
		actions: {
			panTilt: false,
			ptSpeed: false,
			zoom: false,
			zSpeed: false,
			focus: false,
			fSpeed: false,
			OAF: false,
			OTAF: false,
			iris: false,
			gain: { cmd: 'OGS:', dropdown: c.CHOICES_GAIN_UB300 },
			shut: { cmd: 'OSG:5D:', dropdown: c.CHOICES_SHUTTER_UB300 },
			ped: { cmd: 'OSG:4A:', dropdown: c.CHOICES_PEDESTAL_UB300() },
			filter: { cmd: 'OFT:', dropdown: c.CHOICES_FILTER_3 },
			preset: false,
			speedPset: false,
			timePset: false,
			power: false,
			ins: false,
			colorbar: true,
			tally: true,
			tally2: true,
			sdCard: false,
			whiteBalance: false,
			colorTemperature: false,
		},
	},

	{
		// Specific for the AG-CX350/4000 Camera
		id: 'CX350',
		variables: {
			// Camera firmware lacks event update notification support!
			version: false,
			error: false,
			ins: false,
			power: false,
			colorbar: false,
			tally: false,
			tally2: false,
			OAF: false,
			iris: false,
			gainValue: false,
			preset: false,
			whiteBalance: false,
			colorTemperature: false,
		},
		feedbacks: {
			// Camera firmware lacks event update notification support!
			powerState: false,
			colorbarState: false,
			tallyState: false,
			tally2State: false,
			insState: false,
			autoFocus: false,
			autoIris: false,
			whiteBalance: false,
			preset: false,			
		},
		actions: {
			panTilt: false,
			ptSpeed: false,
			zoom: true,
			zSpeed: true,
			focus: true,
			fSpeed: true,
			OAF: true,
			OTAF: true,
			iris: true,
			gain: { cmd: 'OGU:', dropdown: c.CHOICES_GAIN_CX350 },
			shut: false,
			ped: { cmd: 'OSJ:0F:', dropdown: c.CHOICES_PEDESTAL_UE150() },
			filter: { cmd: 'OFT:', dropdown: c.CHOICES_FILTER_3 },
			preset: false,
			speedPset: false,
			timePset: false,
			power: false,
			colorbar: true,
			tally: true,
			tally2: true,
			ins: false,
			sdCard: true,
			whiteBalance: { dropdown: c.CHOICES_WB_SET },
			colorTemperature: false,
		},
	},
]
